### ISSUE TITLE
Issue #1 : Upoznavanje sa zahtjevima projekta

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#1]
Upoznati se sa zahtjevanim funkcionalnostima projekta:
-  razvrstavanje pločica po bojama
- realizacija PC aplikacije koja koristi Wi-Fi za komunikaciju i prikazuje proces razvrstavanja, te pruža mogućnost kontrole rada uređaja
- upravljanje uređaja korištenjem komandi na strani uređaja

**Comment by rankomirosav** [comment]
Tezina zadatka je 3.

**Comment by Chicha13** [comment]
Ocjena tezine (1-10):

3

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 3.

**Comment by natasamiljevic** [comment]
Završeno. Potrebno vrijeme: 2h.
