### ISSUE TITLE
Issue #10 : Projektovanje električne šeme - minimalni broj pinova

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#10]
Za početak rada sa PIC24FJ64GA702 mikrokontrolerom, potrebno je napraviti električnu šemu koja koristi minimalan broj pinova prije nego što se pređe na dalji razvoj, kako je preporučeno u dokumentaciji.

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 5.

**Comment by rankomirosav** [comment]
Težina zadatka je 4.

**Comment by Chicha13** [comment]
Ocjena težine (1-10):

5

**Comment by rankomirosav** [comment]
Vrijeme izrade 30 m.
