### ISSUE TITLE
Issue #11 : Projektovanje električne šeme - Wi-Fi modul

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#11]
Potrebno je dizajnirati električnu šemu koja uključuje Wi-Fi modul.
Šema treba da obuhvati sve osnovne komponente potrebne za povezivanje Wi-Fi modula sa mikrokontrolerom, uključujući napajanje, te komunikacione pinove.

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 8.

**Comment by rankomirosav** [comment]
Težina zadatka je 9.

**Comment by Chicha13** [comment]
Ocjena težine (1-10):

7

**Comment by natasamiljevic** [comment]
Završeno. Potrebno vrijeme: 2h.
