### ISSUE TITLE
Issue #2 : Upoznavanje sa komponentama

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#2]
Upoznati se sa komponentama koje se koriste za realizaciju projekta:

- servomotor
- ace tracking sensor 
- LED lights
- button
- battery case

**Comment by rankomirosav** [comment]
Težina zadatka: 3

**Comment by Chicha13** [comment]
Ocjena tezine (1-10):

4

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 3.

**Comment by Chicha13** [comment]
Završeno. Potrebno vrijeme: 1h 30min.
