### ISSUE TITLE
Issue #3 : Sklapanje konstrukcije

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#3]
Povezati komponente prema uputstvu.

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 1.

**Comment by Chicha13** [comment]
Ocjena tezine (1-10):

1

**Comment by rankomirosav** [comment]
Završeno. Potrebno vrijeme: 15 m. Težina zadataka: 1
