### ISSUE TITLE
Issue #4 : Detekcija potrebnih komponenata

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#4]
Na osnovu zahtjevanih funkcionalnosti projekta detektovati komponente koje nedostaju.

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 4.

**Comment by Chicha13** [comment]
Ocjena težine (1-10):

3

**Comment by rankomirosav** [comment]
Težina zadatak : 4

**Comment by natasamiljevic** [comment]
Završeno. Potrebno vrijeme: 2h.
