### ISSUE TITLE
Issue #5 : Inicijalna analiza dokumentacije za PIC24FJ64GA702 mikrokontroler

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#5]
Cilj je da se identifikuju osnovne karakteristike i funkcionalnosti mikrokontrolera koje su relevantne za potrebe projekta. Analiza će poslužiti kao osnova za detaljnije razmatranje i integraciju mikrokontrolera u sistem.

Koraci:
- Preuzeti i pregledati datasheet za PIC24FJ64GA702.
- Izdvojiti najvažnije karakteristike.
- Razmotriti raspored pinova.

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 4.

**Comment by Chicha13** [comment]
Ocjena težine (1-10):

3

**Comment by rankomirosav** [comment]
Tezina zadatka  je 5

**Comment by natasamiljevic** [comment]
Završeno. Potrebno vrijeme: 2h.
