### ISSUE TITLE
Issue #6 : Projektovanje električne šeme - početna integracija MCU

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#6]
Ovaj issue se odnosi na početnu fazu projektovanja PCB-a za naš sistem, sa fokusom na integraciju mikrokontrolera PIC24FJ64GA702. Električna šema će biti dizajnirana u KiCad softveru, a cilj je projektovati osnovnu šemu sa mikrokontrolerom.

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 4.

**Comment by Chicha13** [comment]
Ocjena težine (1-10):

4

**Comment by rankomirosav** [comment]
Tezina zadatka 9.

**Comment by Chicha13** [comment]
Završeno. Potrebno vrijeme: 1h.
