### ISSUE TITLE
Issue #7 : Analiza sistema za napajanje

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#7]
Koraci:
- Analiza strujnih i naponskih zahtjeva sistema.
- Izbor napajanja za mikrokontroler i komponente.
- Razmatranje baterija i naponskih regulatora.

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 8.

**Comment by rankomirosav** [comment]
Tezina zadatka je 7.

**Comment by Chicha13** [comment]
Ocjena težine (1-10):

7

**Comment by rankomirosav** [comment]
Potrebno vrijeme za izradu 2h.
