### ISSUE TITLE
Issue #8 : Upoznavanje sa ESP8266EX - Serial Interface Wi-Fi Module komponentom

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#8]
Cilj:

- Istražiti osnovne karakteristike ESP8266EX modula, uključujući naponske zahtjeve, interfejs i protokole.
- Proučiti mogućnosti i ograničenja modula, kao i kako ga povezati sa mikrokontrolerom.

**Comment by Chicha13** [comment]
Ocjena težine (1-10):

5

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 5.

**Comment by rankomirosav** [comment]
Težina zadatka je 5.

**Comment by natasamiljevic** [comment]
Završeno. Potrebno vrijeme: 1h.
