### ISSUE TITLE
Issue #9 : Upoznavanje sa Color 10 Click komponentom

### ISSUE THREAD

**Issue by natasamiljevic** [lukavidic/ColorSorter_B#9]
Cilj: Proučiti dokumentaciju za ovu komponentu kako bi se uspješno integrisala u postojeći projekat.

**Comment by Chicha13** [comment]
Ocjena težine (1-10):

5

**Comment by natasamiljevic** [comment]
Težina zadatka na skali od 1 do 10 je 5.

**Comment by rankomirosav** [comment]
Tezina zadatka je 5.

**Comment by Chicha13** [comment]
Završeno. Potrebno vrijeme: 2h.
